#!/bin/bash

# Set terminal color
# printf "\033[1;36;48m" ; clear

# Get current working directory
BASEDIR=$(dirname "$0")

if [ "$BASEDIR" == "." ]; then
   BASEDIR=$(pwd)
fi

mkdir "$BASEDIR/vendors";

# Download rgcr/m-cli
clear;
echo "o------------------------------------------------------------------o";
echo "| macOS IFTTT Control Installer                               v1.0 |";
echo "o------------------------------------------------------------------o";
echo "|                                                                  |";
echo "|   Downloading rgcr/m-cli from GitHub...                          |";
echo "|                                                                  |";
echo "o------------------------------------------------------------------o";

cd $BASEDIR
curl -O https://codeload.github.com/rgcr/m-cli/zip/master >/dev/null 2>&1
mv "master" "master.zip" >/dev/null 2>&1
unzip "master.zip" >/dev/null 2>&1
rm -rf "master.zip" >/dev/null 2>&1
rm -rf "vendors/m-cli-master" >/dev/null 2>&1
mv "m-cli-master" "vendors/m-cli-master" >/dev/null 2>&1

# Install plugins
rm -rf "vendors/m-cli-master/plugins/bluetooth" >/dev/null 2>&1
cp plugins/* "vendors/m-cli-master/plugins" >/dev/null 2>&1

# Check if M-CLI has been downloaded succesfully
if [ ! -d "vendors/m-cli-master" ] 
then
    clear;
    echo "o------------------------------------------------------------------o";
    echo "| macOS IFTTT Control Installer                               v1.0 |";
    echo "o------------------------------------------------------------------o";
    echo "|                                                                  |";
    echo "|   The required files can't be downloaded: rgcr/m-cli             |";
    echo "|                                                                  |";
    echo "|   Please check your internet connection.                         |";
    echo "|                                                                  |";
    echo "o------------------------------------------------------------------o";
    exit;
fi
